### ISSUE TITLE
Problem with saving model when model_per_pair = True

### ISSUE THREAD

**Issue by kblaszczyk1** [nateemma/strategies#16]
Hello, 

All trained currency pairs are always saved to the same model, i.e. to the first pair.

***************************************
** Warning: startup can be very slow **
***************************************

    OS Type:    linux, Version: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.28
    python:     ['3.9.13 (main, Nov 16 2022, 15:11:16) ', '[GCC 8.5.0 20210514 (Red Hat 8.5.0-15.0.1)]']
    sklearn:    1.1.3
    tensorflow: 2.10.0, devices:[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
    keras:      2.10.0
    pytorch:    2.0.0+cu117
    lightning:  1.6.5
    darts:      0.24.0

    Lookahead:  12  candles ( 1.0  hours)

BTC/USDT
future_df: (240609, 127) valleys: (240609,)
    Compressed data 78 -> 64 (features)
    model not found (/opt/strategies/binanceus/models/NNTC_pv_LSTM/NNTC_pv_LSTM_BTC.h5)...
Model: "NNTC_pv_LSTM_BTC"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm (LSTM)                 (None, 64, 128)           98816

 dropout (Dropout)           (None, 64, 128)           0

 dense (Dense)               (None, 64, 3)             387

=================================================================
Total params: 99,203
Trainable params: 99,203
Non-trainable params: 0
_________________________________________________________________

    training model: NNTC_pv_LSTM_BTC...
2023-04-19 15:31:24.832243: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2838151168 exceeds 10% of free system memory.
2023-04-19 15:31:26.337054: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2838151168 exceeds 10% of free system memory.
Epoch 1/256
170/170 [==============================] - 74s 421ms/step - loss: 0.0627 - accuracy: 0.9801 - mse: 0.0106 - val_loss: 0.0479 - val_accuracy: 0.9842 - val_mse: 0.0084 - lr: 0.0100
Epoch 2/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0159 - accuracy: 0.9943 - mse: 0.0030 - val_loss: 0.0543 - val_accuracy: 0.9841 - val_mse: 0.0085 - lr: 0.0100
Epoch 3/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0083 - accuracy: 0.9972 - mse: 0.0015 - val_loss: 0.0720 - val_accuracy: 0.9847 - val_mse: 0.0088 - lr: 0.0100
Epoch 4/256
170/170 [==============================] - 67s 395ms/step - loss: 0.0059 - accuracy: 0.9979 - mse: 0.0011 - val_loss: 0.0811 - val_accuracy: 0.9841 - val_mse: 0.0093 - lr: 0.0100
Epoch 5/256
170/170 [==============================] - 70s 413ms/step - loss: 0.0050 - accuracy: 0.9982 - mse: 9.8364e-04 - val_loss: 0.0956 - val_accuracy: 0.9842 - val_mse: 0.0095 - lr: 0.0100
Epoch 6/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0044 - accuracy: 0.9984 - mse: 8.8681e-04 - val_loss: 0.0964 - val_accuracy: 0.9840 - val_mse: 0.0095 - lr: 0.0100
Epoch 7/256
170/170 [==============================] - 68s 397ms/step - loss: 0.0038 - accuracy: 0.9986 - mse: 7.8178e-04 - val_loss: 0.1097 - val_accuracy: 0.9839 - val_mse: 0.0098 - lr: 0.0100
Epoch 8/256
170/170 [==============================] - 68s 398ms/step - loss: 0.0036 - accuracy: 0.9987 - mse: 7.3245e-04 - val_loss: 0.1111 - val_accuracy: 0.9838 - val_mse: 0.0097 - lr: 0.0100
Epoch 9/256
170/170 [==============================] - 70s 412ms/step - loss: 0.0034 - accuracy: 0.9987 - mse: 7.0511e-04 - val_loss: 0.1171 - val_accuracy: 0.9840 - val_mse: 0.0098 - lr: 0.0100
Epoch 10/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0031 - accuracy: 0.9989 - mse: 6.3571e-04 - val_loss: 0.1190 - val_accuracy: 0.9833 - val_mse: 0.0101 - lr: 0.0100
Epoch 11/256
170/170 [==============================] - 68s 400ms/step - loss: 0.0029 - accuracy: 0.9989 - mse: 6.1432e-04 - val_loss: 0.1254 - val_accuracy: 0.9842 - val_mse: 0.0097 - lr: 0.0100
Epoch 12/256
170/170 [==============================] - 68s 398ms/step - loss: 0.0028 - accuracy: 0.9990 - mse: 5.8455e-04 - val_loss: 0.1261 - val_accuracy: 0.9835 - val_mse: 0.0101 - lr: 0.0100
Epoch 13/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.6473e-04 - val_loss: 0.1344 - val_accuracy: 0.9839 - val_mse: 0.0100 - lr: 0.0100
Epoch 14/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.3535e-04 - val_loss: 0.1397 - val_accuracy: 0.9840 - val_mse: 0.0099 - lr: 0.0100
Epoch 15/256
170/170 [==============================] - 68s 397ms/step - loss: 0.0024 - accuracy: 0.9991 - mse: 5.1931e-04 - val_loss: 0.1401 - val_accuracy: 0.9842 - val_mse: 0.0098 - lr: 0.0100
Epoch 16/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0023 - accuracy: 0.9991 - mse: 4.9947e-04 - val_loss: 0.1370 - val_accuracy: 0.9839 - val_mse: 0.0099 - lr: 0.0100
Epoch 17/256
170/170 [==============================] - 70s 410ms/step - loss: 0.0022 - accuracy: 0.9992 - mse: 4.7225e-04 - val_loss: 0.1418 - val_accuracy: 0.9840 - val_mse: 0.0100 - lr: 0.0100
Epoch 18/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0021 - accuracy: 0.9992 - mse: 4.5977e-04 - val_loss: 0.1438 - val_accuracy: 0.9835 - val_mse: 0.0102 - lr: 0.0100
Epoch 19/256
170/170 [==============================] - 69s 404ms/step - loss: 0.0020 - accuracy: 0.9993 - mse: 4.4544e-04 - val_loss: 0.1436 - val_accuracy: 0.9840 - val_mse: 0.0100 - lr: 0.0100
Epoch 20/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0021 - accuracy: 0.9993 - mse: 4.5012e-04 - val_loss: 0.1513 - val_accuracy: 0.9838 - val_mse: 0.0102 - lr: 0.0100
Epoch 21/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0022 - accuracy: 0.9992 - mse: 4.6581e-04 - val_loss: 0.1600 - val_accuracy: 0.9841 - val_mse: 0.0100 - lr: 0.0100
Epoch 22/256
170/170 [==============================] - 69s 408ms/step - loss: 0.0019 - accuracy: 0.9993 - mse: 4.1997e-04 - val_loss: 0.1515 - val_accuracy: 0.9839 - val_mse: 0.0100 - lr: 0.0100
Epoch 23/256
170/170 [==============================] - 69s 405ms/step - loss: 0.0018 - accuracy: 0.9994 - mse: 3.9421e-04 - val_loss: 0.1679 - val_accuracy: 0.9836 - val_mse: 0.0103 - lr: 0.0100
Epoch 24/256
170/170 [==============================] - 69s 406ms/step - loss: 0.0018 - accuracy: 0.9993 - mse: 3.9958e-04 - val_loss: 0.1570 - val_accuracy: 0.9836 - val_mse: 0.0103 - lr: 0.0100
Epoch 25/256
170/170 [==============================] - 69s 409ms/step - loss: 0.0018 - accuracy: 0.9994 - mse: 3.9310e-04 - val_loss: 0.1614 - val_accuracy: 0.9838 - val_mse: 0.0102 - lr: 0.0100
Epoch 26/256
170/170 [==============================] - 69s 404ms/step - loss: 0.0018 - accuracy: 0.9993 - mse: 3.9796e-04 - val_loss: 0.1573 - val_accuracy: 0.9841 - val_mse: 0.0100 - lr: 0.0100
Epoch 27/256
170/170 [==============================] - 69s 405ms/step - loss: 0.0016 - accuracy: 0.9994 - mse: 3.6293e-04 - val_loss: 0.1642 - val_accuracy: 0.9841 - val_mse: 0.0099 - lr: 0.0100
Epoch 28/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0018 - accuracy: 0.9994 - mse: 3.8912e-04 - val_loss: 0.1515 - val_accuracy: 0.9840 - val_mse: 0.0099 - lr: 0.0100
Epoch 29/256
170/170 [==============================] - 69s 408ms/step - loss: 0.0018 - accuracy: 0.9993 - mse: 3.9439e-04 - val_loss: 0.1546 - val_accuracy: 0.9837 - val_mse: 0.0102 - lr: 0.0100
Epoch 30/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0017 - accuracy: 0.9994 - mse: 3.6521e-04 - val_loss: 0.1649 - val_accuracy: 0.9838 - val_mse: 0.0101 - lr: 0.0100
Epoch 31/256
170/170 [==============================] - 69s 408ms/step - loss: 0.0015 - accuracy: 0.9994 - mse: 3.4641e-04 - val_loss: 0.1685 - val_accuracy: 0.9839 - val_mse: 0.0102 - lr: 0.0100
    saving model to:  /opt/strategies/binanceus/models/NNTC_pv_LSTM/NNTC_pv_LSTM_BTC.h5
    predicting buys/sells...
2023-04-19 16:07:18.335873: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 3942137856 exceeds 10% of free system memory.
2023-04-19 16:07:20.558039: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 3942137856 exceeds 10% of free system memory.

ETH/USDT
future_df: (240609, 127) valleys: (240609,)
    Compressed data 78 -> 64 (features)

    training model: NNTC_pv_LSTM_BTC...
2023-04-19 16:10:53.140993: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2838151168 exceeds 10% of free system memory.
Epoch 1/256
170/170 [==============================] - 86s 494ms/step - loss: 0.0435 - accuracy: 0.9861 - mse: 0.0072 - val_loss: 0.0458 - val_accuracy: 0.9859 - val_mse: 0.0075 - lr: 0.0100
Epoch 2/256
170/170 [==============================] - 71s 415ms/step - loss: 0.0139 - accuracy: 0.9950 - mse: 0.0027 - val_loss: 0.0568 - val_accuracy: 0.9858 - val_mse: 0.0079 - lr: 0.0100
Epoch 3/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0095 - accuracy: 0.9967 - mse: 0.0018 - val_loss: 0.0712 - val_accuracy: 0.9856 - val_mse: 0.0082 - lr: 0.0100
Epoch 4/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0075 - accuracy: 0.9974 - mse: 0.0014 - val_loss: 0.0751 - val_accuracy: 0.9850 - val_mse: 0.0085 - lr: 0.0100
Epoch 5/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0064 - accuracy: 0.9977 - mse: 0.0012 - val_loss: 0.0880 - val_accuracy: 0.9851 - val_mse: 0.0086 - lr: 0.0100
Epoch 6/256
170/170 [==============================] - 71s 415ms/step - loss: 0.0057 - accuracy: 0.9980 - mse: 0.0011 - val_loss: 0.0958 - val_accuracy: 0.9852 - val_mse: 0.0087 - lr: 0.0100
Epoch 7/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0051 - accuracy: 0.9981 - mse: 0.0010 - val_loss: 0.0983 - val_accuracy: 0.9849 - val_mse: 0.0088 - lr: 0.0100
Epoch 8/256
170/170 [==============================] - 67s 396ms/step - loss: 0.0048 - accuracy: 0.9983 - mse: 9.4561e-04 - val_loss: 0.0997 - val_accuracy: 0.9849 - val_mse: 0.0089 - lr: 0.0100
Epoch 9/256
170/170 [==============================] - 67s 395ms/step - loss: 0.0045 - accuracy: 0.9984 - mse: 8.9343e-04 - val_loss: 0.1003 - val_accuracy: 0.9848 - val_mse: 0.0089 - lr: 0.0100
Epoch 10/256
170/170 [==============================] - 67s 396ms/step - loss: 0.0042 - accuracy: 0.9985 - mse: 8.4716e-04 - val_loss: 0.1152 - val_accuracy: 0.9848 - val_mse: 0.0091 - lr: 0.0100
Epoch 11/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0040 - accuracy: 0.9985 - mse: 8.0412e-04 - val_loss: 0.1209 - val_accuracy: 0.9848 - val_mse: 0.0091 - lr: 0.0100
Epoch 12/256
170/170 [==============================] - 67s 396ms/step - loss: 0.0038 - accuracy: 0.9986 - mse: 7.6672e-04 - val_loss: 0.1201 - val_accuracy: 0.9847 - val_mse: 0.0092 - lr: 0.0100
Epoch 13/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0036 - accuracy: 0.9987 - mse: 7.3962e-04 - val_loss: 0.1267 - val_accuracy: 0.9845 - val_mse: 0.0094 - lr: 0.0100
Epoch 14/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0034 - accuracy: 0.9987 - mse: 7.1005e-04 - val_loss: 0.1267 - val_accuracy: 0.9848 - val_mse: 0.0092 - lr: 0.0100
Epoch 15/256
170/170 [==============================] - 68s 400ms/step - loss: 0.0034 - accuracy: 0.9987 - mse: 6.9885e-04 - val_loss: 0.1351 - val_accuracy: 0.9846 - val_mse: 0.0094 - lr: 0.0100
Epoch 16/256
170/170 [==============================] - 68s 398ms/step - loss: 0.0032 - accuracy: 0.9988 - mse: 6.7116e-04 - val_loss: 0.1352 - val_accuracy: 0.9846 - val_mse: 0.0094 - lr: 0.0100
Epoch 17/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0031 - accuracy: 0.9989 - mse: 6.4307e-04 - val_loss: 0.1471 - val_accuracy: 0.9845 - val_mse: 0.0095 - lr: 0.0100
Epoch 18/256
170/170 [==============================] - 67s 395ms/step - loss: 0.0030 - accuracy: 0.9989 - mse: 6.2865e-04 - val_loss: 0.1359 - val_accuracy: 0.9842 - val_mse: 0.0095 - lr: 0.0100
Epoch 19/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0029 - accuracy: 0.9989 - mse: 6.1851e-04 - val_loss: 0.1529 - val_accuracy: 0.9841 - val_mse: 0.0097 - lr: 0.0100
Epoch 20/256
170/170 [==============================] - 68s 398ms/step - loss: 0.0028 - accuracy: 0.9989 - mse: 6.0146e-04 - val_loss: 0.1536 - val_accuracy: 0.9841 - val_mse: 0.0097 - lr: 0.0100
Epoch 21/256
170/170 [==============================] - 67s 396ms/step - loss: 0.0028 - accuracy: 0.9990 - mse: 5.8356e-04 - val_loss: 0.1561 - val_accuracy: 0.9843 - val_mse: 0.0096 - lr: 0.0100
Epoch 22/256
170/170 [==============================] - 68s 398ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.6902e-04 - val_loss: 0.1602 - val_accuracy: 0.9846 - val_mse: 0.0095 - lr: 0.0100
Epoch 23/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.7623e-04 - val_loss: 0.1611 - val_accuracy: 0.9843 - val_mse: 0.0096 - lr: 0.0100
Epoch 24/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.7155e-04 - val_loss: 0.1677 - val_accuracy: 0.9846 - val_mse: 0.0096 - lr: 0.0100
Epoch 25/256
170/170 [==============================] - 67s 397ms/step - loss: 0.0026 - accuracy: 0.9990 - mse: 5.5055e-04 - val_loss: 0.1519 - val_accuracy: 0.9840 - val_mse: 0.0097 - lr: 0.0100
Epoch 26/256
170/170 [==============================] - 68s 399ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.4096e-04 - val_loss: 0.1646 - val_accuracy: 0.9836 - val_mse: 0.0099 - lr: 0.0100
Epoch 27/256
170/170 [==============================] - 67s 394ms/step - loss: 0.0024 - accuracy: 0.9991 - mse: 5.2668e-04 - val_loss: 0.1763 - val_accuracy: 0.9840 - val_mse: 0.0098 - lr: 0.0100
Epoch 28/256
170/170 [==============================] - 67s 394ms/step - loss: 0.0023 - accuracy: 0.9991 - mse: 5.0323e-04 - val_loss: 0.1834 - val_accuracy: 0.9844 - val_mse: 0.0097 - lr: 0.0100
Epoch 29/256
170/170 [==============================] - 67s 394ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.2721e-04 - val_loss: 0.1746 - val_accuracy: 0.9841 - val_mse: 0.0098 - lr: 0.0100
Epoch 30/256
170/170 [==============================] - 67s 396ms/step - loss: 0.0023 - accuracy: 0.9991 - mse: 5.0593e-04 - val_loss: 0.1747 - val_accuracy: 0.9844 - val_mse: 0.0096 - lr: 0.0100
Epoch 31/256
170/170 [==============================] - 67s 393ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.2943e-04 - val_loss: 0.1788 - val_accuracy: 0.9841 - val_mse: 0.0098 - lr: 0.0100
Epoch 32/256
170/170 [==============================] - 67s 394ms/step - loss: 0.0023 - accuracy: 0.9991 - mse: 4.9479e-04 - val_loss: 0.1699 - val_accuracy: 0.9841 - val_mse: 0.0097 - lr: 0.0100
    saving model to:  /opt/strategies/binanceus/models/NNTC_pv_LSTM/NNTC_pv_LSTM_BTC.h5
    predicting buys/sells...

LTC/USDT
future_df: (240609, 127) valleys: (240609,)
    Compressed data 78 -> 64 (features)

    training model: NNTC_pv_LSTM_BTC...
Epoch 1/256
170/170 [==============================] - 77s 443ms/step - loss: 0.0300 - accuracy: 0.9891 - mse: 0.0055 - val_loss: 0.0474 - val_accuracy: 0.9839 - val_mse: 0.0082 - lr: 0.0100
Epoch 2/256
170/170 [==============================] - 69s 407ms/step - loss: 0.0114 - accuracy: 0.9959 - mse: 0.0022 - val_loss: 0.0593 - val_accuracy: 0.9838 - val_mse: 0.0087 - lr: 0.0100
Epoch 3/256
170/170 [==============================] - 69s 404ms/step - loss: 0.0081 - accuracy: 0.9972 - mse: 0.0015 - val_loss: 0.0667 - val_accuracy: 0.9838 - val_mse: 0.0089 - lr: 0.0100
Epoch 4/256
170/170 [==============================] - 69s 404ms/step - loss: 0.0066 - accuracy: 0.9977 - mse: 0.0012 - val_loss: 0.0738 - val_accuracy: 0.9836 - val_mse: 0.0091 - lr: 0.0100
Epoch 5/256
170/170 [==============================] - 70s 409ms/step - loss: 0.0057 - accuracy: 0.9980 - mse: 0.0011 - val_loss: 0.0779 - val_accuracy: 0.9832 - val_mse: 0.0094 - lr: 0.0100
Epoch 6/256
170/170 [==============================] - 69s 406ms/step - loss: 0.0052 - accuracy: 0.9982 - mse: 9.9670e-04 - val_loss: 0.0846 - val_accuracy: 0.9833 - val_mse: 0.0095 - lr: 0.0100
Epoch 7/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0048 - accuracy: 0.9983 - mse: 9.2480e-04 - val_loss: 0.0886 - val_accuracy: 0.9833 - val_mse: 0.0095 - lr: 0.0100
Epoch 8/256
170/170 [==============================] - 68s 400ms/step - loss: 0.0045 - accuracy: 0.9984 - mse: 8.6852e-04 - val_loss: 0.0896 - val_accuracy: 0.9829 - val_mse: 0.0097 - lr: 0.0100
Epoch 9/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0042 - accuracy: 0.9985 - mse: 8.1712e-04 - val_loss: 0.0966 - val_accuracy: 0.9833 - val_mse: 0.0097 - lr: 0.0100
Epoch 10/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0039 - accuracy: 0.9986 - mse: 7.6950e-04 - val_loss: 0.0959 - val_accuracy: 0.9829 - val_mse: 0.0098 - lr: 0.0100
Epoch 11/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0038 - accuracy: 0.9987 - mse: 7.5141e-04 - val_loss: 0.0949 - val_accuracy: 0.9829 - val_mse: 0.0099 - lr: 0.0100
Epoch 12/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0036 - accuracy: 0.9987 - mse: 7.2022e-04 - val_loss: 0.1078 - val_accuracy: 0.9830 - val_mse: 0.0099 - lr: 0.0100
Epoch 13/256
170/170 [==============================] - 69s 403ms/step - loss: 0.0035 - accuracy: 0.9988 - mse: 6.9908e-04 - val_loss: 0.1116 - val_accuracy: 0.9826 - val_mse: 0.0102 - lr: 0.0100
Epoch 14/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0034 - accuracy: 0.9988 - mse: 6.7164e-04 - val_loss: 0.1128 - val_accuracy: 0.9828 - val_mse: 0.0102 - lr: 0.0100
Epoch 15/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0033 - accuracy: 0.9988 - mse: 6.5499e-04 - val_loss: 0.1107 - val_accuracy: 0.9824 - val_mse: 0.0103 - lr: 0.0100
Epoch 16/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0033 - accuracy: 0.9988 - mse: 6.6342e-04 - val_loss: 0.1181 - val_accuracy: 0.9826 - val_mse: 0.0102 - lr: 0.0100
Epoch 17/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0032 - accuracy: 0.9989 - mse: 6.5039e-04 - val_loss: 0.1088 - val_accuracy: 0.9824 - val_mse: 0.0102 - lr: 0.0100
Epoch 18/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0032 - accuracy: 0.9989 - mse: 6.4083e-04 - val_loss: 0.1294 - val_accuracy: 0.9829 - val_mse: 0.0103 - lr: 0.0100
Epoch 19/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0030 - accuracy: 0.9989 - mse: 6.0872e-04 - val_loss: 0.1296 - val_accuracy: 0.9832 - val_mse: 0.0101 - lr: 0.0100
Epoch 20/256
170/170 [==============================] - 68s 400ms/step - loss: 0.0030 - accuracy: 0.9990 - mse: 5.9834e-04 - val_loss: 0.1313 - val_accuracy: 0.9830 - val_mse: 0.0101 - lr: 0.0100
Epoch 21/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0030 - accuracy: 0.9990 - mse: 6.0337e-04 - val_loss: 0.1273 - val_accuracy: 0.9825 - val_mse: 0.0104 - lr: 0.0100
Epoch 22/256
170/170 [==============================] - 68s 401ms/step - loss: 0.0029 - accuracy: 0.9990 - mse: 5.9306e-04 - val_loss: 0.1291 - val_accuracy: 0.9822 - val_mse: 0.0106 - lr: 0.0100
Epoch 23/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0029 - accuracy: 0.9990 - mse: 5.8325e-04 - val_loss: 0.1259 - val_accuracy: 0.9827 - val_mse: 0.0103 - lr: 0.0100
Epoch 24/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0028 - accuracy: 0.9990 - mse: 5.6829e-04 - val_loss: 0.1242 - val_accuracy: 0.9826 - val_mse: 0.0104 - lr: 0.0100
Epoch 25/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.5997e-04 - val_loss: 0.1421 - val_accuracy: 0.9830 - val_mse: 0.0103 - lr: 0.0100
Epoch 26/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.6065e-04 - val_loss: 0.1363 - val_accuracy: 0.9823 - val_mse: 0.0105 - lr: 0.0100
Epoch 27/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0027 - accuracy: 0.9990 - mse: 5.5150e-04 - val_loss: 0.1385 - val_accuracy: 0.9825 - val_mse: 0.0105 - lr: 0.0100
Epoch 28/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0026 - accuracy: 0.9991 - mse: 5.2845e-04 - val_loss: 0.1379 - val_accuracy: 0.9822 - val_mse: 0.0106 - lr: 0.0100
Epoch 29/256
170/170 [==============================] - 68s 402ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.1997e-04 - val_loss: 0.1328 - val_accuracy: 0.9825 - val_mse: 0.0104 - lr: 0.0100
Epoch 30/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.1954e-04 - val_loss: 0.1437 - val_accuracy: 0.9828 - val_mse: 0.0104 - lr: 0.0100
Epoch 31/256
170/170 [==============================] - 68s 403ms/step - loss: 0.0026 - accuracy: 0.9991 - mse: 5.3735e-04 - val_loss: 0.1352 - val_accuracy: 0.9831 - val_mse: 0.0102 - lr: 0.0100
Epoch 32/256
170/170 [==============================] - 69s 404ms/step - loss: 0.0025 - accuracy: 0.9991 - mse: 5.1632e-04 - val_loss: 0.1401 - val_accuracy: 0.9828 - val_mse: 0.0104 - lr: 0.0100
    saving model to:  /opt/strategies/binanceus/models/NNTC_pv_LSTM/NNTC_pv_LSTM_BTC.h5

**Comment by nateemma** [comment]
I haven't tested that for a while, I'll take a look

Thanks,

Phil

**Comment by nateemma** [comment]
OK, it should be fixed now. You just need to update NNTC.py

Thanks,

Phil

**Comment by kblaszczyk1** [comment]
Thanks Phil!
