### ISSUE TITLE
How fix this error? I am using NNTC_pv_LSTM + ShortTradeDurHyperOptLoss

### ISSUE THREAD

**Issue by maledicente** [nateemma/strategies#28]
Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    0/1000   0% • 0:00:17 • -:--:--WARNING:tensorflow:From /freqtrade/user_data/strategies/ClassifierKeras.py:44: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

WARNING:tensorflow:From /freqtrade/user_data/strategies/ClassifierKeras.py:44: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    0/1000   0% • 0:00:17 • -:--:--WARNING:tensorflow:From /freqtrade/user_data/strategies/ClassifierKeras.py:44: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    0/1000   0% • 0:00:17 • -:--:--WARNING:tensorflow:From /freqtrade/user_data/strategies/ClassifierKeras.py:44: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

Epochs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    0/1000   0% • 0:00:18 • -:--:--
2023-05-08 22:19:29,633 - freqtrade - ERROR - Fatal exception!
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/ftuser/.local/lib/python3.10/site-packages/joblib/externals/loky/cloudpickle_wrapper.py", line 43, in _reconstruct_wrapper
    obj = loads(_pickled_object)
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 48, in deserialize_model_from_bytecode
    raise e
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/saving/pickle_utils.py", line 46, in deserialize_model_from_bytecode
    model = saving_lib.load_model(filepath, safe_mode=False)
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 277, in load_model
    raise e
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/saving/saving_lib.py", line 242, in load_model
    model = deserialize_keras_object(
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/saving/serialization_lib.py", line 508, in deserialize_keras_object
    instance.compile_from_config(compile_config)
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/engine/training.py", line 3392, in compile_from_config
    self.optimizer.build(self.trainable_variables)
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/optimizers/legacy/optimizer_v2.py", line 984, in __getattribute__
    raise e
  File "/home/ftuser/.local/lib/python3.10/site-packages/keras/optimizers/legacy/optimizer_v2.py", line 974, in __getattribute__
    return super().__getattribute__(name)
AttributeError: 'Adam' object has no attribute 'build'
"""

**Comment by nateemma** [comment]
Can you send me the full output please?
From what I can see here, it looks like there is an error loading the
model. Did you change anything related to the neural network algorithm or
the number of inputs?

Thanks

Phil

**Comment by maledicente** [comment]
I'm using docker in oracle-cloud/ubuntu, i didn't change any party of the code.

**Comment by mmsquantum** [comment]
lmao

**Comment by nateemma** [comment]
Hmm, it works for me.

Can you send the full output please? I especially need to see the text at
the top of the run (it shows version numbers etc.)


Also, can you run the following command please (and send me the output)?:

h5ls -r user_data/strategies/binanceus/models/NNTC_pv_LSTM/NNTC_pv_LSTM.h5


(I'm assuming you are running from the binanceus exchange, if not, change
that to the location you are using)



if you don't have h5ls installed, you can get it using the following
command:

sudo apt-get install libhdf5-dev

Thanks,

Phil

**Comment by maledicente** [comment]
h5ls NNTC_pv_LSTM_ACH.h5

(base) ubuntu@bot-swarm:~/freqtrade/user_data/strategies/models/NNTC_pv_LSTM$ h5ls -r NNTC_pv_LSTM_ACH.h5
/                        Group
/model_weights           Group
/model_weights/dense     Group
/model_weights/dense/dense Group
/model_weights/dense/dense/bias:0 Dataset {3}
/model_weights/dense/dense/kernel:0 Dataset {128, 3}
/model_weights/dropout   Group
/model_weights/lstm      Group
/model_weights/lstm/lstm Group
/model_weights/lstm/lstm/lstm_cell Group
/model_weights/lstm/lstm/lstm_cell/bias:0 Dataset {512}
/model_weights/lstm/lstm/lstm_cell/kernel:0 Dataset {64, 512}
/model_weights/lstm/lstm/lstm_cell/recurrent_kernel:0 Dataset {128, 512}
/model_weights/top_level_model_weights Group
/optimizer_weights       Group
/optimizer_weights/Adam  Group
/optimizer_weights/Adam/dense Group
/optimizer_weights/Adam/dense/bias Group
/optimizer_weights/Adam/dense/bias/m:0 Dataset {3}
/optimizer_weights/Adam/dense/bias/v:0 Dataset {3}
/optimizer_weights/Adam/dense/kernel Group
/optimizer_weights/Adam/dense/kernel/m:0 Dataset {128, 3}
/optimizer_weights/Adam/dense/kernel/v:0 Dataset {128, 3}
/optimizer_weights/Adam/iter:0 Dataset {SCALAR}
/optimizer_weights/Adam/lstm Group
/optimizer_weights/Adam/lstm/lstm_cell Group
/optimizer_weights/Adam/lstm/lstm_cell/bias Group
/optimizer_weights/Adam/lstm/lstm_cell/bias/m:0 Dataset {512}
/optimizer_weights/Adam/lstm/lstm_cell/bias/v:0 Dataset {512}
/optimizer_weights/Adam/lstm/lstm_cell/kernel Group
/optimizer_weights/Adam/lstm/lstm_cell/kernel/m:0 Dataset {64, 512}
/optimizer_weights/Adam/lstm/lstm_cell/kernel/v:0 Dataset {64, 512}
/optimizer_weights/Adam/lstm/lstm_cell/recurrent_kernel Group
/optimizer_weights/Adam/lstm/lstm_cell/recurrent_kernel/m:0 Dataset {128, 512}
/optimizer_weights/Adam/lstm/lstm_cell/recurrent_kernel/v:0 Dataset {128, 512}

**Comment by nateemma** [comment]
the model parameters look OK. Can you send me the full output of a test run
please?

You can also just generate your own model as follows - but this will take a
long time (and see notes at the end):

# remove existing models
rm -r user_data/strategies/models/NNTC_pv_LSTM

# download pair data
zsh user_data/strategies/scripts/download.sh -n 750 binanceus

# generate new model
zsh user_data/strategies/scripts/test_strat.sh -n 750 binanceus NNTC_pv_LSTM

# run hyperopt (optional, but suggested)
zsh user_data/strategies/scripts/hyp_strat.sh -n 90 -e 100 binanceus
NNTC_pv_LSTM

Notes:
- you have model_per_pair set to True. You can speed up training by setting
this to False (maybe try this with the existing model). This will then use
a single model (user_data/strategies/models/NNTC_pv_LSTM/NNTC_pv_LSTM.h5)
for all pairs
- I typically train models over ~2 years of data (750 days). If you just
want to see it runs, use a shorter time period; it will work, but just
won't be a good model

Thanks,

Phil

**Comment by nateemma** [comment]
or, if you wait a week or so, I am in the middle of re-writing parts of
NNTC and will re-generate models. It takes me about a week to generate all
the models though 😡

Thanks,

Phil

**Comment by maledicente** [comment]
There are anything wrong with the backtest

[output.txt](https://github.com/nateemma/strategies/files/11492609/output.txt)

**Comment by nateemma** [comment]
The results look too good, which usually means that you have something
forward-looking in your technical indicators. Did you add any?

Thanks

Phil

**Comment by nateemma** [comment]
OK, I cannot find any lookahead bias. However, I notice that the returns
are extremely sensitive to the time period used. My suspicion is that the
performance is good because your training and test data overlap (i.e. you
are testing with some of the data that you also used for training). I
will take a look at excluding the last 30 days (for example) of data from
any training/verification and see how that works...

Cheers,

Phil
