### ISSUE TITLE
Can't get DWT_predict to work

### ISSUE THREAD

**Issue by donmega** [nateemma/strategies#31]
Hi,

I can't seem to get DWT_Predict working. I've installed all the dependencies, but i am still getting errors.

![Screenshot 2023-06-27 at 22 16 05](https://github.com/nateemma/strategies/assets/10058942/c3602716-ea5c-42f5-ac7a-b56c51bda44b)

![Screenshot 2023-06-27 at 22 16 49](https://github.com/nateemma/strategies/assets/10058942/4732f831-0e75-4d0f-8ee6-39f38bbf95b6)

Thank you, and keep up the great work!

**Comment by nateemma** [comment]
it looks like you have python errors, which would imply that you need to
install the needed packages. The only non-standard one used by DWT_Predict
is PyWavelets, so try the following from inside your virtual environment:

pip3 install PyWavelets

hope that helps.

Thanks,

Phil

**Comment by donmega** [comment]
Hi Phil,

PyWavelets was already installed. I messed up when trying to change some Python code. Fixed now :).
Thank you so much for your hard work!

Cheers!

**Comment by nateemma** [comment]
anything you need added? Also, still making changes...

Thanks,

Phil

**Comment by donmega** [comment]
Yea, I've only added 5x leverage, i messed up the syntax :).
Thanks once again for your help!
