### ISSUE TITLE
Some questions about training and optimization

### ISSUE THREAD

**Issue by maledicente** [nateemma/strategies#41]
I always use docker. I created an image with the requirements in the Dockerfile, it works well.
Can I train TS_Gain normally or is there a specific configuration in zsh?

back_b_ia:
     image: freqtrade_ia
     restart: on-failure
     container_name: back_b_ia
     volumes:
       - "./user_data:/freqtrade/user_data"
     command: >
       backtesting
       --datadir user_data/data/${EXCHANGE:-binance}
       -c user_data/config-exchange-general.json
       -c /freqtrade/user_data/bot_binance_ia.json
       -c user_data/pair_lists/api_binance.json
       -c user_data/pair_lists/blacklist-binance.json
       -c user_data/pair_lists/api_binance.json
       -c user_data/config-telegram-general.json
       --max-open-trades ${MAX_OPEN_TRADES:-6}
       --strategy-list TSPredict TS_Gain 
       -c user_data/pair_lists/pairlist-backtest-static-binance-spot-usdt.json
       --data-format-ohlcv feather
       --timeframe 5m
       --dry-run-wallet 100
       --timerange ${TIMERANGE:-20220101-20231207}
     CPU: '48'
     mem_limit: 500G
     memswap_limit: -1
     
     
 I have tried to use your script in a ubuntu machine, but zsh: can't open input file: user_data/strategies/scripts/test_strat
freqtrade_local/freqtrade$ zsh user_data/strategies/scripts/test_strat -n 600 TSPredict TS_Gain

**Comment by nateemma** [comment]
Oops, the instructions are slightly wrong - you need to add .sh to
test_strat:

zsh user_data/strategies/scripts/test_strat.sh -n 600 TSPredict TS_Gain

If you haven't changed the indicators, you (usually) don't need to
re-generate the model

Thanks,

Phil

**Comment by maledicente** [comment]
Okay, here -n 600 TS Predict TS Gain
-n = 600 days? In Docker, can I directly train Ts_Gain with the commands above in back_b_ia?
I'm slowly studying your algorithms, it's quite dense to understand hehe

**Comment by nateemma** [comment]
I don't quite understand your question. What is back_b_ia?

Anyway, not sure if this will help:

- the command:
zsh user_data/strategies/scripts/test_strat.sh -n 600 TSPredict TS_Gain
is running the script test_strat.sh over the last 600 days, and is running
the strategy TS_Gain.py in directory TSPredict

- if a model file already exists (in
user_data/strategies/TSPredict/models/TS_Gain) then it will load that and
use it as the basis for making predictions. If it does not exist, then it
will train a new model and save it - in this case it will not make any
predictions. I usually only run for long time periods when I am creating a
new model. I would normally only test for about 30 days (or less)

- TSPredict.py is the base class of all of the strategies in this
directory, and provides the main framework for loading/saving models,
backtesting, populating buy/sell signals and handling custom stoploss/exit
functionality.

- There are several 'families' of strategies: TS_Gain, TS_Simple, TS_Coeff
and TS_Wavelet right now. Each of these overrides functions of TSPredict to
implement a type of approach. For example, TS_Gain just predicts the future
gain, it doesn't use any other indicators.

- there are variants within each family that might use different prediction
algorithms (as in TS_Gain and TS_Simple), or different ways of modelling
the signal (as in TS_Coeff and TS_Wavelet)

Hope that helps. Feel free to ask more questions, I know it's pretty
complicated

Thanks,

Phil
