### ISSUE TITLE
TS_Wavelet_FFT for futures

### ISSUE THREAD

**Issue by maledicente** [nateemma/strategies#42]
I intend to create TS_Wavelet_FFT for future 3x, any tips?

**Comment by tomjrtsmith** [comment]
I've been having a bit of trouble getting leverage callback to work with
the overlay strategies so let me know how you get on. Need to include
'optional' for the lev callback.

**Comment by maledicente** [comment]
![image](https://github.com/nateemma/strategies/assets/39028554/d2e2a138-c901-4091-942f-f53593c47722)

**Comment by tomjrtsmith** [comment]
So did you put the lev callback in the overlay strat?

I find if you run it in the TS_Predict base class it won't run in the
overlay.

**Comment by maledicente** [comment]
I put in TS_Predict, works
